name: ghost_chat
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.3.0
  bloc: ^8.0.1
  cloud_firestore: ^3.1.4
  contacts_service: ^0.6.3
  cryptography: ^2.0.5
  cupertino_icons: ^1.0.2
  encrypt: ^5.0.1
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  firebase_storage: ^10.2.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  hydrated_bloc: ^8.0.0
  image: ^3.1.0
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  ml_linalg: ^13.0.2
  path: ^1.8.0
  path_provider: ^2.0.8
  permission_handler: ^8.3.0
  sizer: ^2.0.15
  sqflite: ^2.0.1
  stream_transform: ^2.0.0
  timeago: ^3.1.0
  uuid: ^3.0.5

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  test: ^1.15.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
